spring.application.name=campping-backend


external.gocamping.base-url=https://apis.data.go.kr/B551011/GoCamping
external.gocamping.service-key=Xxbo7HKWs%2BJMHeY4jGqrboMo7tLLPtgGyp4nZtlXUSZdzhbS9VzsfufYZFvwV%2BOmDuOwoSfiWO2CmoD7bqzUdw%3D%3D
external.gocamping.mobile-os=ETC
external.gocamping.mobile-app=REST


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/campping?serverTimezone=Asia/Seoul&characterEncoding=utf8&useUnicode=true
spring.datasource.username=root
spring.datasource.password=1234